### ISSUE TITLE
Sony A7 IV has 12bit readout and lossy compression in high-speed continuous

### ISSUE THREAD

**Issue by michalkochanowicz** [horshack-dpreview/RollingShutter#2]
Hi Horshack,

Thank you for creating this page, it is awesome!

I just would like to suggest adding a comment to A7 IV, that at high speed (when the readout is faster at 1/32 instead of 1/15) it performs 12bit readout and forces lossy compression.

This information was useful to me, so maybe others would be interested.

Source: https://www.dpreview.com/reviews/sony-a7-iv-review

Cheers!

**Comment by horshack-dpreview** [comment]
Hi,

The testing protocol includes checks for bit depth / readout time changes for continuous shooting modes. You can see these details by clicking on the model name in the live table. For example here's the information for the A7 IV:

[https://horshack-dpreview.github.io/RollingShutter/#Sony%20A7%20IV](url)

**Comment by michalkochanowicz** [comment]
I see a comment about 12bit in R6 II, but not in A7 IV. So you say DPR is wrong and A7 IV reads 14 bits in highest speed mode?
![image](https://github.com/horshack-dpreview/RollingShutter/assets/13177326/38896d2a-8793-40e3-9b96-7df92f41eb2c)

**Comment by horshack-dpreview** [comment]
The drop in bit depth is implied by the increase in readout speed for tested continuous modes, the same as how it's implied by the increase in readout speed on some sensors at higher ISOs. And how sensor subsampling for certain videos mode is implied by an increase in readout speeds vs their non-subsampled modes. The R6 II's baseline bit depth of 12-bits for stills cannot be implied because there is no slower stills-mode readout speed to compare it to.
